// Generated register struct for SPI_DEVICE

// Copyright information found in source file:
// Copyright lowRISC contributors.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#[allow(unused_imports)]
use kernel::utilities::registers::{
    register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly,
};

register_structs! {
    pub Spi_DeviceRegisters {
        (0x0 => intr_state: ReadWrite<u32, INTR_STATE::Register>),
        (0x4 => intr_enable: ReadWrite<u32, INTR_ENABLE::Register>),
        (0x8 => intr_test: WriteOnly<u32, INTR_TEST::Register>),
        (0xc => alert_test: WriteOnly<u32, ALERT_TEST::Register>),
        (0x10 => control: ReadWrite<u32, CONTROL::Register>),
        (0x14 => cfg: ReadWrite<u32, CFG::Register>),
        (0x18 => fifo_level: ReadWrite<u32, FIFO_LEVEL::Register>),
        (0x1c => async_fifo_level: ReadOnly<u32, ASYNC_FIFO_LEVEL::Register>),
        (0x20 => status: ReadOnly<u32, STATUS::Register>),
        (0x24 => rxf_ptr: ReadWrite<u32, RXF_PTR::Register>),
        (0x28 => txf_ptr: ReadWrite<u32, TXF_PTR::Register>),
        (0x2c => rxf_addr: ReadWrite<u32, RXF_ADDR::Register>),
        (0x30 => txf_addr: ReadWrite<u32, TXF_ADDR::Register>),
        (0x34 => last_read_addr: ReadOnly<u32, LAST_READ_ADDR::Register>),
        (0x38 => flash_status: ReadWrite<u32, FLASH_STATUS::Register>),
        (0x3c => jedec_id: ReadWrite<u32, JEDEC_ID::Register>),
        (0x40 => read_threshold: ReadWrite<u32, READ_THRESHOLD::Register>),
        (0x44 => upload_status: ReadOnly<u32, UPLOAD_STATUS::Register>),
        (0x48 => upload_cmdfifo: ReadOnly<u32, UPLOAD_CMDFIFO::Register>),
        (0x4c => upload_addrfifo: ReadOnly<u32, UPLOAD_ADDRFIFO::Register>),
        (0x50 => cmd_filter_0: ReadWrite<u32, CMD_FILTER_0::Register>),
        (0x54 => cmd_filter_1: ReadWrite<u32, CMD_FILTER_1::Register>),
        (0x58 => cmd_filter_2: ReadWrite<u32, CMD_FILTER_2::Register>),
        (0x5c => cmd_filter_3: ReadWrite<u32, CMD_FILTER_3::Register>),
        (0x60 => cmd_filter_4: ReadWrite<u32, CMD_FILTER_4::Register>),
        (0x64 => cmd_filter_5: ReadWrite<u32, CMD_FILTER_5::Register>),
        (0x68 => cmd_filter_6: ReadWrite<u32, CMD_FILTER_6::Register>),
        (0x6c => cmd_filter_7: ReadWrite<u32, CMD_FILTER_7::Register>),
        (0x70 => addr_swap_mask: ReadWrite<u32, ADDR_SWAP_MASK::Register>),
        (0x74 => addr_swap_data: ReadWrite<u32, ADDR_SWAP_DATA::Register>),
        (0x78 => cmd_info_0: ReadWrite<u32, CMD_INFO_0::Register>),
        (0x7c => cmd_info_1: ReadWrite<u32, CMD_INFO_1::Register>),
        (0x80 => cmd_info_2: ReadWrite<u32, CMD_INFO_2::Register>),
        (0x84 => cmd_info_3: ReadWrite<u32, CMD_INFO_3::Register>),
        (0x88 => cmd_info_4: ReadWrite<u32, CMD_INFO_4::Register>),
        (0x8c => cmd_info_5: ReadWrite<u32, CMD_INFO_5::Register>),
        (0x90 => cmd_info_6: ReadWrite<u32, CMD_INFO_6::Register>),
        (0x94 => cmd_info_7: ReadWrite<u32, CMD_INFO_7::Register>),
        (0x98 => cmd_info_8: ReadWrite<u32, CMD_INFO_8::Register>),
        (0x9c => cmd_info_9: ReadWrite<u32, CMD_INFO_9::Register>),
        (0xa0 => cmd_info_10: ReadWrite<u32, CMD_INFO_10::Register>),
        (0xa4 => cmd_info_11: ReadWrite<u32, CMD_INFO_11::Register>),
        (0xa8 => cmd_info_12: ReadWrite<u32, CMD_INFO_12::Register>),
        (0xac => cmd_info_13: ReadWrite<u32, CMD_INFO_13::Register>),
        (0xb0 => cmd_info_14: ReadWrite<u32, CMD_INFO_14::Register>),
        (0xb4 => cmd_info_15: ReadWrite<u32, CMD_INFO_15::Register>),
        (0xb8 => cmd_info_16: ReadWrite<u32, CMD_INFO_16::Register>),
        (0xbc => cmd_info_17: ReadWrite<u32, CMD_INFO_17::Register>),
        (0xc0 => cmd_info_18: ReadWrite<u32, CMD_INFO_18::Register>),
        (0xc4 => cmd_info_19: ReadWrite<u32, CMD_INFO_19::Register>),
        (0xc8 => cmd_info_20: ReadWrite<u32, CMD_INFO_20::Register>),
        (0xcc => cmd_info_21: ReadWrite<u32, CMD_INFO_21::Register>),
        (0xd0 => cmd_info_22: ReadWrite<u32, CMD_INFO_22::Register>),
        (0xd4 => cmd_info_23: ReadWrite<u32, CMD_INFO_23::Register>),
        (0x800 => tpm_cap: ReadOnly<u32, TPM_CAP::Register>),
        (0x804 => tpm_cfg: ReadWrite<u32, TPM_CFG::Register>),
        (0x808 => tpm_status: ReadOnly<u32, TPM_STATUS::Register>),
        (0x80c => tpm_access_0: ReadWrite<u32, TPM_ACCESS_0::Register>),
        (0x810 => tpm_access_1: ReadWrite<u32, TPM_ACCESS_1::Register>),
        (0x814 => tpm_sts: ReadWrite<u32, TPM_STS::Register>),
        (0x818 => tpm_intf_capability: ReadWrite<u32, TPM_INTF_CAPABILITY::Register>),
        (0x81c => tpm_int_enable: ReadWrite<u32, TPM_INT_ENABLE::Register>),
        (0x820 => tpm_int_vector: ReadWrite<u32, TPM_INT_VECTOR::Register>),
        (0x824 => tpm_int_status: ReadWrite<u32, TPM_INT_STATUS::Register>),
        (0x828 => tpm_did_vid: ReadWrite<u32, TPM_DID_VID::Register>),
        (0x82c => tpm_rid: ReadWrite<u32, TPM_RID::Register>),
        (0x830 => tpm_cmd_addr: ReadOnly<u32, TPM_CMD_ADDR::Register>),
        (0x834 => tpm_read_fifo: WriteOnly<u32, TPM_READ_FIFO::Register>),
        (0x838 => tpm_write_fifo: ReadOnly<u32, TPM_WRITE_FIFO::Register>),
    }
}

register_bitfields![u32,
    INTR_STATE [
        RXF OFFSET(0) NUMBITS(1) [],
        RXLVL OFFSET(1) NUMBITS(1) [],
        TXLVL OFFSET(2) NUMBITS(1) [],
        RXERR OFFSET(3) NUMBITS(1) [],
        RXOVERFLOW OFFSET(4) NUMBITS(1) [],
        TXUNDERFLOW OFFSET(5) NUMBITS(1) [],
        TPM_CMDADDR_NOTEMPTY OFFSET(6) NUMBITS(1) [],
    ],
    INTR_ENABLE [
        RXF OFFSET(0) NUMBITS(1) [],
        RXLVL OFFSET(1) NUMBITS(1) [],
        TXLVL OFFSET(2) NUMBITS(1) [],
        RXERR OFFSET(3) NUMBITS(1) [],
        RXOVERFLOW OFFSET(4) NUMBITS(1) [],
        TXUNDERFLOW OFFSET(5) NUMBITS(1) [],
        TPM_CMDADDR_NOTEMPTY OFFSET(6) NUMBITS(1) [],
    ],
    INTR_TEST [
        RXF OFFSET(0) NUMBITS(1) [],
        RXLVL OFFSET(1) NUMBITS(1) [],
        TXLVL OFFSET(2) NUMBITS(1) [],
        RXERR OFFSET(3) NUMBITS(1) [],
        RXOVERFLOW OFFSET(4) NUMBITS(1) [],
        TXUNDERFLOW OFFSET(5) NUMBITS(1) [],
        TPM_CMDADDR_NOTEMPTY OFFSET(6) NUMBITS(1) [],
    ],
    ALERT_TEST [
        FATAL_FAULT OFFSET(0) NUMBITS(1) [],
    ],
    CONTROL [
        ABORT OFFSET(0) NUMBITS(1) [],
        MODE OFFSET(4) NUMBITS(2) [
            FWMODE = 0,
        ],
        RST_TXFIFO OFFSET(16) NUMBITS(1) [],
        RST_RXFIFO OFFSET(17) NUMBITS(1) [],
        SRAM_CLK_EN OFFSET(31) NUMBITS(1) [],
    ],
    CFG [
        CPOL OFFSET(0) NUMBITS(1) [],
        CPHA OFFSET(1) NUMBITS(1) [],
        TX_ORDER OFFSET(2) NUMBITS(1) [],
        RX_ORDER OFFSET(3) NUMBITS(1) [],
        TIMER_V OFFSET(8) NUMBITS(8) [],
        ADDR_4B_EN OFFSET(16) NUMBITS(1) [],
    ],
    FIFO_LEVEL [
        RXLVL OFFSET(0) NUMBITS(16) [],
        TXLVL OFFSET(16) NUMBITS(16) [],
    ],
    ASYNC_FIFO_LEVEL [
        RXLVL OFFSET(0) NUMBITS(8) [],
        TXLVL OFFSET(16) NUMBITS(8) [],
    ],
    STATUS [
        RXF_FULL OFFSET(0) NUMBITS(1) [],
        RXF_EMPTY OFFSET(1) NUMBITS(1) [],
        TXF_FULL OFFSET(2) NUMBITS(1) [],
        TXF_EMPTY OFFSET(3) NUMBITS(1) [],
        ABORT_DONE OFFSET(4) NUMBITS(1) [],
        CSB OFFSET(5) NUMBITS(1) [],
    ],
    RXF_PTR [
        RPTR OFFSET(0) NUMBITS(16) [],
        WPTR OFFSET(16) NUMBITS(16) [],
    ],
    TXF_PTR [
        RPTR OFFSET(0) NUMBITS(16) [],
        WPTR OFFSET(16) NUMBITS(16) [],
    ],
    RXF_ADDR [
        BASE OFFSET(0) NUMBITS(16) [],
        LIMIT OFFSET(16) NUMBITS(16) [],
    ],
    TXF_ADDR [
        BASE OFFSET(0) NUMBITS(16) [],
        LIMIT OFFSET(16) NUMBITS(16) [],
    ],
    LAST_READ_ADDR [
        ADDR OFFSET(0) NUMBITS(32) [],
    ],
    FLASH_STATUS [
        BUSY OFFSET(0) NUMBITS(1) [],
        STATUS OFFSET(1) NUMBITS(23) [],
    ],
    JEDEC_ID [
        ID OFFSET(0) NUMBITS(16) [],
        MF OFFSET(16) NUMBITS(8) [],
    ],
    READ_THRESHOLD [
        THRESHOLD OFFSET(0) NUMBITS(10) [],
    ],
    UPLOAD_STATUS [
        CMDFIFO_DEPTH OFFSET(0) NUMBITS(5) [],
        CMDFIFO_NOTEMPTY OFFSET(7) NUMBITS(1) [],
        ADDRFIFO_DEPTH OFFSET(8) NUMBITS(5) [],
        ADDRFIFO_NOTEMPTY OFFSET(15) NUMBITS(1) [],
        PAYLOAD_DEPTH OFFSET(16) NUMBITS(9) [],
    ],
    UPLOAD_CMDFIFO [
        DATA OFFSET(0) NUMBITS(8) [],
    ],
    UPLOAD_ADDRFIFO [
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    CMD_FILTER_0 [
        FILTER_0 OFFSET(0) NUMBITS(1) [],
        FILTER_1 OFFSET(1) NUMBITS(1) [],
        FILTER_2 OFFSET(2) NUMBITS(1) [],
        FILTER_3 OFFSET(3) NUMBITS(1) [],
        FILTER_4 OFFSET(4) NUMBITS(1) [],
        FILTER_5 OFFSET(5) NUMBITS(1) [],
        FILTER_6 OFFSET(6) NUMBITS(1) [],
        FILTER_7 OFFSET(7) NUMBITS(1) [],
        FILTER_8 OFFSET(8) NUMBITS(1) [],
        FILTER_9 OFFSET(9) NUMBITS(1) [],
        FILTER_10 OFFSET(10) NUMBITS(1) [],
        FILTER_11 OFFSET(11) NUMBITS(1) [],
        FILTER_12 OFFSET(12) NUMBITS(1) [],
        FILTER_13 OFFSET(13) NUMBITS(1) [],
        FILTER_14 OFFSET(14) NUMBITS(1) [],
        FILTER_15 OFFSET(15) NUMBITS(1) [],
        FILTER_16 OFFSET(16) NUMBITS(1) [],
        FILTER_17 OFFSET(17) NUMBITS(1) [],
        FILTER_18 OFFSET(18) NUMBITS(1) [],
        FILTER_19 OFFSET(19) NUMBITS(1) [],
        FILTER_20 OFFSET(20) NUMBITS(1) [],
        FILTER_21 OFFSET(21) NUMBITS(1) [],
        FILTER_22 OFFSET(22) NUMBITS(1) [],
        FILTER_23 OFFSET(23) NUMBITS(1) [],
        FILTER_24 OFFSET(24) NUMBITS(1) [],
        FILTER_25 OFFSET(25) NUMBITS(1) [],
        FILTER_26 OFFSET(26) NUMBITS(1) [],
        FILTER_27 OFFSET(27) NUMBITS(1) [],
        FILTER_28 OFFSET(28) NUMBITS(1) [],
        FILTER_29 OFFSET(29) NUMBITS(1) [],
        FILTER_30 OFFSET(30) NUMBITS(1) [],
        FILTER_31 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_1 [
        FILTER_32 OFFSET(0) NUMBITS(1) [],
        FILTER_33 OFFSET(1) NUMBITS(1) [],
        FILTER_34 OFFSET(2) NUMBITS(1) [],
        FILTER_35 OFFSET(3) NUMBITS(1) [],
        FILTER_36 OFFSET(4) NUMBITS(1) [],
        FILTER_37 OFFSET(5) NUMBITS(1) [],
        FILTER_38 OFFSET(6) NUMBITS(1) [],
        FILTER_39 OFFSET(7) NUMBITS(1) [],
        FILTER_40 OFFSET(8) NUMBITS(1) [],
        FILTER_41 OFFSET(9) NUMBITS(1) [],
        FILTER_42 OFFSET(10) NUMBITS(1) [],
        FILTER_43 OFFSET(11) NUMBITS(1) [],
        FILTER_44 OFFSET(12) NUMBITS(1) [],
        FILTER_45 OFFSET(13) NUMBITS(1) [],
        FILTER_46 OFFSET(14) NUMBITS(1) [],
        FILTER_47 OFFSET(15) NUMBITS(1) [],
        FILTER_48 OFFSET(16) NUMBITS(1) [],
        FILTER_49 OFFSET(17) NUMBITS(1) [],
        FILTER_50 OFFSET(18) NUMBITS(1) [],
        FILTER_51 OFFSET(19) NUMBITS(1) [],
        FILTER_52 OFFSET(20) NUMBITS(1) [],
        FILTER_53 OFFSET(21) NUMBITS(1) [],
        FILTER_54 OFFSET(22) NUMBITS(1) [],
        FILTER_55 OFFSET(23) NUMBITS(1) [],
        FILTER_56 OFFSET(24) NUMBITS(1) [],
        FILTER_57 OFFSET(25) NUMBITS(1) [],
        FILTER_58 OFFSET(26) NUMBITS(1) [],
        FILTER_59 OFFSET(27) NUMBITS(1) [],
        FILTER_60 OFFSET(28) NUMBITS(1) [],
        FILTER_61 OFFSET(29) NUMBITS(1) [],
        FILTER_62 OFFSET(30) NUMBITS(1) [],
        FILTER_63 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_2 [
        FILTER_64 OFFSET(0) NUMBITS(1) [],
        FILTER_65 OFFSET(1) NUMBITS(1) [],
        FILTER_66 OFFSET(2) NUMBITS(1) [],
        FILTER_67 OFFSET(3) NUMBITS(1) [],
        FILTER_68 OFFSET(4) NUMBITS(1) [],
        FILTER_69 OFFSET(5) NUMBITS(1) [],
        FILTER_70 OFFSET(6) NUMBITS(1) [],
        FILTER_71 OFFSET(7) NUMBITS(1) [],
        FILTER_72 OFFSET(8) NUMBITS(1) [],
        FILTER_73 OFFSET(9) NUMBITS(1) [],
        FILTER_74 OFFSET(10) NUMBITS(1) [],
        FILTER_75 OFFSET(11) NUMBITS(1) [],
        FILTER_76 OFFSET(12) NUMBITS(1) [],
        FILTER_77 OFFSET(13) NUMBITS(1) [],
        FILTER_78 OFFSET(14) NUMBITS(1) [],
        FILTER_79 OFFSET(15) NUMBITS(1) [],
        FILTER_80 OFFSET(16) NUMBITS(1) [],
        FILTER_81 OFFSET(17) NUMBITS(1) [],
        FILTER_82 OFFSET(18) NUMBITS(1) [],
        FILTER_83 OFFSET(19) NUMBITS(1) [],
        FILTER_84 OFFSET(20) NUMBITS(1) [],
        FILTER_85 OFFSET(21) NUMBITS(1) [],
        FILTER_86 OFFSET(22) NUMBITS(1) [],
        FILTER_87 OFFSET(23) NUMBITS(1) [],
        FILTER_88 OFFSET(24) NUMBITS(1) [],
        FILTER_89 OFFSET(25) NUMBITS(1) [],
        FILTER_90 OFFSET(26) NUMBITS(1) [],
        FILTER_91 OFFSET(27) NUMBITS(1) [],
        FILTER_92 OFFSET(28) NUMBITS(1) [],
        FILTER_93 OFFSET(29) NUMBITS(1) [],
        FILTER_94 OFFSET(30) NUMBITS(1) [],
        FILTER_95 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_3 [
        FILTER_96 OFFSET(0) NUMBITS(1) [],
        FILTER_97 OFFSET(1) NUMBITS(1) [],
        FILTER_98 OFFSET(2) NUMBITS(1) [],
        FILTER_99 OFFSET(3) NUMBITS(1) [],
        FILTER_100 OFFSET(4) NUMBITS(1) [],
        FILTER_101 OFFSET(5) NUMBITS(1) [],
        FILTER_102 OFFSET(6) NUMBITS(1) [],
        FILTER_103 OFFSET(7) NUMBITS(1) [],
        FILTER_104 OFFSET(8) NUMBITS(1) [],
        FILTER_105 OFFSET(9) NUMBITS(1) [],
        FILTER_106 OFFSET(10) NUMBITS(1) [],
        FILTER_107 OFFSET(11) NUMBITS(1) [],
        FILTER_108 OFFSET(12) NUMBITS(1) [],
        FILTER_109 OFFSET(13) NUMBITS(1) [],
        FILTER_110 OFFSET(14) NUMBITS(1) [],
        FILTER_111 OFFSET(15) NUMBITS(1) [],
        FILTER_112 OFFSET(16) NUMBITS(1) [],
        FILTER_113 OFFSET(17) NUMBITS(1) [],
        FILTER_114 OFFSET(18) NUMBITS(1) [],
        FILTER_115 OFFSET(19) NUMBITS(1) [],
        FILTER_116 OFFSET(20) NUMBITS(1) [],
        FILTER_117 OFFSET(21) NUMBITS(1) [],
        FILTER_118 OFFSET(22) NUMBITS(1) [],
        FILTER_119 OFFSET(23) NUMBITS(1) [],
        FILTER_120 OFFSET(24) NUMBITS(1) [],
        FILTER_121 OFFSET(25) NUMBITS(1) [],
        FILTER_122 OFFSET(26) NUMBITS(1) [],
        FILTER_123 OFFSET(27) NUMBITS(1) [],
        FILTER_124 OFFSET(28) NUMBITS(1) [],
        FILTER_125 OFFSET(29) NUMBITS(1) [],
        FILTER_126 OFFSET(30) NUMBITS(1) [],
        FILTER_127 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_4 [
        FILTER_128 OFFSET(0) NUMBITS(1) [],
        FILTER_129 OFFSET(1) NUMBITS(1) [],
        FILTER_130 OFFSET(2) NUMBITS(1) [],
        FILTER_131 OFFSET(3) NUMBITS(1) [],
        FILTER_132 OFFSET(4) NUMBITS(1) [],
        FILTER_133 OFFSET(5) NUMBITS(1) [],
        FILTER_134 OFFSET(6) NUMBITS(1) [],
        FILTER_135 OFFSET(7) NUMBITS(1) [],
        FILTER_136 OFFSET(8) NUMBITS(1) [],
        FILTER_137 OFFSET(9) NUMBITS(1) [],
        FILTER_138 OFFSET(10) NUMBITS(1) [],
        FILTER_139 OFFSET(11) NUMBITS(1) [],
        FILTER_140 OFFSET(12) NUMBITS(1) [],
        FILTER_141 OFFSET(13) NUMBITS(1) [],
        FILTER_142 OFFSET(14) NUMBITS(1) [],
        FILTER_143 OFFSET(15) NUMBITS(1) [],
        FILTER_144 OFFSET(16) NUMBITS(1) [],
        FILTER_145 OFFSET(17) NUMBITS(1) [],
        FILTER_146 OFFSET(18) NUMBITS(1) [],
        FILTER_147 OFFSET(19) NUMBITS(1) [],
        FILTER_148 OFFSET(20) NUMBITS(1) [],
        FILTER_149 OFFSET(21) NUMBITS(1) [],
        FILTER_150 OFFSET(22) NUMBITS(1) [],
        FILTER_151 OFFSET(23) NUMBITS(1) [],
        FILTER_152 OFFSET(24) NUMBITS(1) [],
        FILTER_153 OFFSET(25) NUMBITS(1) [],
        FILTER_154 OFFSET(26) NUMBITS(1) [],
        FILTER_155 OFFSET(27) NUMBITS(1) [],
        FILTER_156 OFFSET(28) NUMBITS(1) [],
        FILTER_157 OFFSET(29) NUMBITS(1) [],
        FILTER_158 OFFSET(30) NUMBITS(1) [],
        FILTER_159 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_5 [
        FILTER_160 OFFSET(0) NUMBITS(1) [],
        FILTER_161 OFFSET(1) NUMBITS(1) [],
        FILTER_162 OFFSET(2) NUMBITS(1) [],
        FILTER_163 OFFSET(3) NUMBITS(1) [],
        FILTER_164 OFFSET(4) NUMBITS(1) [],
        FILTER_165 OFFSET(5) NUMBITS(1) [],
        FILTER_166 OFFSET(6) NUMBITS(1) [],
        FILTER_167 OFFSET(7) NUMBITS(1) [],
        FILTER_168 OFFSET(8) NUMBITS(1) [],
        FILTER_169 OFFSET(9) NUMBITS(1) [],
        FILTER_170 OFFSET(10) NUMBITS(1) [],
        FILTER_171 OFFSET(11) NUMBITS(1) [],
        FILTER_172 OFFSET(12) NUMBITS(1) [],
        FILTER_173 OFFSET(13) NUMBITS(1) [],
        FILTER_174 OFFSET(14) NUMBITS(1) [],
        FILTER_175 OFFSET(15) NUMBITS(1) [],
        FILTER_176 OFFSET(16) NUMBITS(1) [],
        FILTER_177 OFFSET(17) NUMBITS(1) [],
        FILTER_178 OFFSET(18) NUMBITS(1) [],
        FILTER_179 OFFSET(19) NUMBITS(1) [],
        FILTER_180 OFFSET(20) NUMBITS(1) [],
        FILTER_181 OFFSET(21) NUMBITS(1) [],
        FILTER_182 OFFSET(22) NUMBITS(1) [],
        FILTER_183 OFFSET(23) NUMBITS(1) [],
        FILTER_184 OFFSET(24) NUMBITS(1) [],
        FILTER_185 OFFSET(25) NUMBITS(1) [],
        FILTER_186 OFFSET(26) NUMBITS(1) [],
        FILTER_187 OFFSET(27) NUMBITS(1) [],
        FILTER_188 OFFSET(28) NUMBITS(1) [],
        FILTER_189 OFFSET(29) NUMBITS(1) [],
        FILTER_190 OFFSET(30) NUMBITS(1) [],
        FILTER_191 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_6 [
        FILTER_192 OFFSET(0) NUMBITS(1) [],
        FILTER_193 OFFSET(1) NUMBITS(1) [],
        FILTER_194 OFFSET(2) NUMBITS(1) [],
        FILTER_195 OFFSET(3) NUMBITS(1) [],
        FILTER_196 OFFSET(4) NUMBITS(1) [],
        FILTER_197 OFFSET(5) NUMBITS(1) [],
        FILTER_198 OFFSET(6) NUMBITS(1) [],
        FILTER_199 OFFSET(7) NUMBITS(1) [],
        FILTER_200 OFFSET(8) NUMBITS(1) [],
        FILTER_201 OFFSET(9) NUMBITS(1) [],
        FILTER_202 OFFSET(10) NUMBITS(1) [],
        FILTER_203 OFFSET(11) NUMBITS(1) [],
        FILTER_204 OFFSET(12) NUMBITS(1) [],
        FILTER_205 OFFSET(13) NUMBITS(1) [],
        FILTER_206 OFFSET(14) NUMBITS(1) [],
        FILTER_207 OFFSET(15) NUMBITS(1) [],
        FILTER_208 OFFSET(16) NUMBITS(1) [],
        FILTER_209 OFFSET(17) NUMBITS(1) [],
        FILTER_210 OFFSET(18) NUMBITS(1) [],
        FILTER_211 OFFSET(19) NUMBITS(1) [],
        FILTER_212 OFFSET(20) NUMBITS(1) [],
        FILTER_213 OFFSET(21) NUMBITS(1) [],
        FILTER_214 OFFSET(22) NUMBITS(1) [],
        FILTER_215 OFFSET(23) NUMBITS(1) [],
        FILTER_216 OFFSET(24) NUMBITS(1) [],
        FILTER_217 OFFSET(25) NUMBITS(1) [],
        FILTER_218 OFFSET(26) NUMBITS(1) [],
        FILTER_219 OFFSET(27) NUMBITS(1) [],
        FILTER_220 OFFSET(28) NUMBITS(1) [],
        FILTER_221 OFFSET(29) NUMBITS(1) [],
        FILTER_222 OFFSET(30) NUMBITS(1) [],
        FILTER_223 OFFSET(31) NUMBITS(1) [],
    ],
    CMD_FILTER_7 [
        FILTER_224 OFFSET(0) NUMBITS(1) [],
        FILTER_225 OFFSET(1) NUMBITS(1) [],
        FILTER_226 OFFSET(2) NUMBITS(1) [],
        FILTER_227 OFFSET(3) NUMBITS(1) [],
        FILTER_228 OFFSET(4) NUMBITS(1) [],
        FILTER_229 OFFSET(5) NUMBITS(1) [],
        FILTER_230 OFFSET(6) NUMBITS(1) [],
        FILTER_231 OFFSET(7) NUMBITS(1) [],
        FILTER_232 OFFSET(8) NUMBITS(1) [],
        FILTER_233 OFFSET(9) NUMBITS(1) [],
        FILTER_234 OFFSET(10) NUMBITS(1) [],
        FILTER_235 OFFSET(11) NUMBITS(1) [],
        FILTER_236 OFFSET(12) NUMBITS(1) [],
        FILTER_237 OFFSET(13) NUMBITS(1) [],
        FILTER_238 OFFSET(14) NUMBITS(1) [],
        FILTER_239 OFFSET(15) NUMBITS(1) [],
        FILTER_240 OFFSET(16) NUMBITS(1) [],
        FILTER_241 OFFSET(17) NUMBITS(1) [],
        FILTER_242 OFFSET(18) NUMBITS(1) [],
        FILTER_243 OFFSET(19) NUMBITS(1) [],
        FILTER_244 OFFSET(20) NUMBITS(1) [],
        FILTER_245 OFFSET(21) NUMBITS(1) [],
        FILTER_246 OFFSET(22) NUMBITS(1) [],
        FILTER_247 OFFSET(23) NUMBITS(1) [],
        FILTER_248 OFFSET(24) NUMBITS(1) [],
        FILTER_249 OFFSET(25) NUMBITS(1) [],
        FILTER_250 OFFSET(26) NUMBITS(1) [],
        FILTER_251 OFFSET(27) NUMBITS(1) [],
        FILTER_252 OFFSET(28) NUMBITS(1) [],
        FILTER_253 OFFSET(29) NUMBITS(1) [],
        FILTER_254 OFFSET(30) NUMBITS(1) [],
        FILTER_255 OFFSET(31) NUMBITS(1) [],
    ],
    ADDR_SWAP_MASK [
        MASK OFFSET(0) NUMBITS(32) [],
    ],
    ADDR_SWAP_DATA [
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    CMD_INFO_0 [
        OPCODE_0 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_0 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_0 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_0 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_0 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_0 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_0 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_0 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_0 OFFSET(20) NUMBITS(1) [],
        UPLOAD_0 OFFSET(24) NUMBITS(1) [],
        BUSY_0 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_1 [
        OPCODE_1 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_1 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_1 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_1 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_1 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_1 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_1 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_1 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_1 OFFSET(20) NUMBITS(1) [],
        UPLOAD_1 OFFSET(24) NUMBITS(1) [],
        BUSY_1 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_2 [
        OPCODE_2 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_2 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_2 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_2 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_2 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_2 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_2 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_2 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_2 OFFSET(20) NUMBITS(1) [],
        UPLOAD_2 OFFSET(24) NUMBITS(1) [],
        BUSY_2 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_3 [
        OPCODE_3 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_3 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_3 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_3 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_3 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_3 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_3 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_3 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_3 OFFSET(20) NUMBITS(1) [],
        UPLOAD_3 OFFSET(24) NUMBITS(1) [],
        BUSY_3 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_4 [
        OPCODE_4 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_4 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_4 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_4 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_4 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_4 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_4 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_4 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_4 OFFSET(20) NUMBITS(1) [],
        UPLOAD_4 OFFSET(24) NUMBITS(1) [],
        BUSY_4 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_5 [
        OPCODE_5 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_5 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_5 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_5 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_5 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_5 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_5 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_5 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_5 OFFSET(20) NUMBITS(1) [],
        UPLOAD_5 OFFSET(24) NUMBITS(1) [],
        BUSY_5 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_6 [
        OPCODE_6 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_6 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_6 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_6 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_6 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_6 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_6 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_6 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_6 OFFSET(20) NUMBITS(1) [],
        UPLOAD_6 OFFSET(24) NUMBITS(1) [],
        BUSY_6 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_7 [
        OPCODE_7 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_7 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_7 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_7 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_7 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_7 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_7 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_7 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_7 OFFSET(20) NUMBITS(1) [],
        UPLOAD_7 OFFSET(24) NUMBITS(1) [],
        BUSY_7 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_8 [
        OPCODE_8 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_8 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_8 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_8 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_8 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_8 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_8 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_8 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_8 OFFSET(20) NUMBITS(1) [],
        UPLOAD_8 OFFSET(24) NUMBITS(1) [],
        BUSY_8 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_9 [
        OPCODE_9 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_9 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_9 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_9 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_9 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_9 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_9 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_9 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_9 OFFSET(20) NUMBITS(1) [],
        UPLOAD_9 OFFSET(24) NUMBITS(1) [],
        BUSY_9 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_10 [
        OPCODE_10 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_10 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_10 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_10 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_10 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_10 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_10 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_10 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_10 OFFSET(20) NUMBITS(1) [],
        UPLOAD_10 OFFSET(24) NUMBITS(1) [],
        BUSY_10 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_11 [
        OPCODE_11 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_11 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_11 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_11 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_11 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_11 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_11 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_11 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_11 OFFSET(20) NUMBITS(1) [],
        UPLOAD_11 OFFSET(24) NUMBITS(1) [],
        BUSY_11 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_12 [
        OPCODE_12 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_12 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_12 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_12 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_12 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_12 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_12 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_12 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_12 OFFSET(20) NUMBITS(1) [],
        UPLOAD_12 OFFSET(24) NUMBITS(1) [],
        BUSY_12 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_13 [
        OPCODE_13 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_13 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_13 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_13 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_13 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_13 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_13 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_13 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_13 OFFSET(20) NUMBITS(1) [],
        UPLOAD_13 OFFSET(24) NUMBITS(1) [],
        BUSY_13 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_14 [
        OPCODE_14 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_14 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_14 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_14 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_14 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_14 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_14 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_14 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_14 OFFSET(20) NUMBITS(1) [],
        UPLOAD_14 OFFSET(24) NUMBITS(1) [],
        BUSY_14 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_15 [
        OPCODE_15 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_15 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_15 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_15 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_15 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_15 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_15 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_15 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_15 OFFSET(20) NUMBITS(1) [],
        UPLOAD_15 OFFSET(24) NUMBITS(1) [],
        BUSY_15 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_16 [
        OPCODE_16 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_16 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_16 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_16 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_16 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_16 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_16 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_16 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_16 OFFSET(20) NUMBITS(1) [],
        UPLOAD_16 OFFSET(24) NUMBITS(1) [],
        BUSY_16 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_17 [
        OPCODE_17 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_17 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_17 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_17 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_17 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_17 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_17 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_17 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_17 OFFSET(20) NUMBITS(1) [],
        UPLOAD_17 OFFSET(24) NUMBITS(1) [],
        BUSY_17 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_18 [
        OPCODE_18 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_18 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_18 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_18 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_18 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_18 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_18 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_18 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_18 OFFSET(20) NUMBITS(1) [],
        UPLOAD_18 OFFSET(24) NUMBITS(1) [],
        BUSY_18 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_19 [
        OPCODE_19 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_19 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_19 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_19 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_19 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_19 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_19 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_19 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_19 OFFSET(20) NUMBITS(1) [],
        UPLOAD_19 OFFSET(24) NUMBITS(1) [],
        BUSY_19 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_20 [
        OPCODE_20 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_20 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_20 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_20 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_20 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_20 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_20 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_20 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_20 OFFSET(20) NUMBITS(1) [],
        UPLOAD_20 OFFSET(24) NUMBITS(1) [],
        BUSY_20 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_21 [
        OPCODE_21 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_21 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_21 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_21 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_21 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_21 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_21 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_21 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_21 OFFSET(20) NUMBITS(1) [],
        UPLOAD_21 OFFSET(24) NUMBITS(1) [],
        BUSY_21 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_22 [
        OPCODE_22 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_22 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_22 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_22 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_22 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_22 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_22 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_22 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_22 OFFSET(20) NUMBITS(1) [],
        UPLOAD_22 OFFSET(24) NUMBITS(1) [],
        BUSY_22 OFFSET(25) NUMBITS(1) [],
    ],
    CMD_INFO_23 [
        OPCODE_23 OFFSET(0) NUMBITS(8) [],
        ADDR_EN_23 OFFSET(8) NUMBITS(1) [],
        ADDR_SWAP_EN_23 OFFSET(9) NUMBITS(1) [],
        ADDR_4B_AFFECTED_23 OFFSET(10) NUMBITS(1) [],
        MBYTE_EN_23 OFFSET(11) NUMBITS(1) [],
        DUMMY_SIZE_23 OFFSET(12) NUMBITS(3) [],
        DUMMY_EN_23 OFFSET(15) NUMBITS(1) [],
        PAYLOAD_EN_23 OFFSET(16) NUMBITS(4) [],
        PAYLOAD_DIR_23 OFFSET(20) NUMBITS(1) [],
        UPLOAD_23 OFFSET(24) NUMBITS(1) [],
        BUSY_23 OFFSET(25) NUMBITS(1) [],
    ],
    TPM_CAP [
        REV OFFSET(0) NUMBITS(8) [],
        LOCALITY OFFSET(8) NUMBITS(1) [],
        MAX_XFER_SIZE OFFSET(16) NUMBITS(3) [],
    ],
    TPM_CFG [
        EN OFFSET(0) NUMBITS(1) [],
        TPM_MODE OFFSET(1) NUMBITS(1) [],
        HW_REG_DIS OFFSET(2) NUMBITS(1) [],
        TPM_REG_CHK_DIS OFFSET(3) NUMBITS(1) [],
        INVALID_LOCALITY OFFSET(4) NUMBITS(1) [],
    ],
    TPM_STATUS [
        CMDADDR_NOTEMPTY OFFSET(0) NUMBITS(1) [],
        RDFIFO_NOTEMPTY OFFSET(1) NUMBITS(1) [],
        RDFIFO_DEPTH OFFSET(4) NUMBITS(3) [],
        WRFIFO_DEPTH OFFSET(8) NUMBITS(3) [],
    ],
    TPM_ACCESS_0 [
        ACCESS_0 OFFSET(0) NUMBITS(8) [],
        ACCESS_1 OFFSET(8) NUMBITS(8) [],
        ACCESS_2 OFFSET(16) NUMBITS(8) [],
        ACCESS_3 OFFSET(24) NUMBITS(8) [],
    ],
    TPM_ACCESS_1 [
        ACCESS_4 OFFSET(0) NUMBITS(8) [],
    ],
    TPM_STS [
        STS OFFSET(0) NUMBITS(32) [],
    ],
    TPM_INTF_CAPABILITY [
        INTF_CAPABILITY OFFSET(0) NUMBITS(32) [],
    ],
    TPM_INT_ENABLE [
        INT_ENABLE OFFSET(0) NUMBITS(32) [],
    ],
    TPM_INT_VECTOR [
        INT_VECTOR OFFSET(0) NUMBITS(8) [],
    ],
    TPM_INT_STATUS [
        INT_STATUS OFFSET(0) NUMBITS(32) [],
    ],
    TPM_DID_VID [
        VID OFFSET(0) NUMBITS(16) [],
        DID OFFSET(16) NUMBITS(16) [],
    ],
    TPM_RID [
        RID OFFSET(0) NUMBITS(8) [],
    ],
    TPM_CMD_ADDR [
        ADDR OFFSET(0) NUMBITS(24) [],
        CMD OFFSET(24) NUMBITS(8) [],
    ],
    TPM_READ_FIFO [
        VALUE OFFSET(0) NUMBITS(8) [],
    ],
    TPM_WRITE_FIFO [
        VALUE OFFSET(0) NUMBITS(8) [],
    ],
];

// Number of alerts
pub const SPI_DEVICE_PARAM_NUM_ALERTS: u32 = 1;

// Register width
pub const SPI_DEVICE_PARAM_REG_WIDTH: u32 = 32;

// Command Filter
pub const SPI_DEVICE_CMD_FILTER_FILTER_FIELD_WIDTH: u32 = 1;
pub const SPI_DEVICE_CMD_FILTER_FILTER_FIELDS_PER_REG: u32 = 32;
pub const SPI_DEVICE_CMD_FILTER_MULTIREG_COUNT: u32 = 8;

// TPM_ACCESS_x register. (common parameters)
pub const SPI_DEVICE_TPM_ACCESS_ACCESS_FIELD_WIDTH: u32 = 8;
pub const SPI_DEVICE_TPM_ACCESS_ACCESS_FIELDS_PER_REG: u32 = 4;
pub const SPI_DEVICE_TPM_ACCESS_MULTIREG_COUNT: u32 = 2;

// Memory area: SPI internal buffer.
pub const SPI_DEVICE_BUFFER_REG_OFFSET: usize = 0x1000;
pub const SPI_DEVICE_BUFFER_SIZE_WORDS: u32 = 1024;
pub const SPI_DEVICE_BUFFER_SIZE_BYTES: u32 = 4096;
// End generated register constants for SPI_DEVICE

