# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.
# Copyright (c) 2024 Antmicro <www.antmicro.com>

# Makefile for building the tock kernel for the VeeR EL2 simulation platform

TARGET=riscv32imc-unknown-none-elf
PLATFORM=veer_el2_sim

include ../Makefile.common

# Default target for installing the kernel.
.PHONY: install
