// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2024.

//! Higher-level Rust interrupt handlers

use crate::registers::irq::EXCEPTIONS;

/// Handler for CPU exceptions generated by the kernel itself.
// `allow(unsupported_calling_conventions)`: cdecl is not valid when testing
// this code on an x86_64 machine. This avoids a warning until a more permanent
// fix is decided. See: https://github.com/tock/tock/pull/4662
#[allow(unsupported_calling_conventions)]
#[no_mangle]
extern "cdecl" fn handle_kernel_exception(num: u32, err: u32, eip: u32) -> ! {
    panic!(
        "{} (error code: {:#x}, eip: {:#x})",
        EXCEPTIONS[num as usize], err, eip
    )
}
