# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

# TARGET=thumbv7em-none-eabi
# PLATFORM=nrf52840dk-test-dynamic-app-load

include ../../../Makefile.common
include ../nrf52840dk.mk
