# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

TARGET=thumbv7em-none-eabi
PLATFORM=nrf52840dk-hotp-tutorial

include ../../Makefile.common
include ../../configurations/nrf52840dk/nrf52840dk.mk
