// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.

// Adapted from embassy-rs/embassy/embassy-stm32/src/rcc/u5.rs

use super::hertz::Hertz;
use super::{
    Rcc,
    values::{
        AHBPrescaler, APBPrescaler, Adcdacsel, Adfsel, Dacsel, Fdcansel, I2c3sel, I2csel, Iclksel,
        Lptim2sel, Lptimsel, Lpusartsel, MsiRange, Octospisel, PllDiv, PllMul, PllPreDiv,
        PllSource, Rngsel, Rtcsel, Saessel, Saisel, Sdmmcsel, Spi1sel, Spi2sel, Spi3sel, Sysclk,
        Usart1sel, Usartsel,
    },
};
use crate::pwr::VoltageScale;

/// Configuration structure for the RCC
///
/// Note: HSI16 (16Mhz oscillator) is always enabled, as a safe fallback for SYSCLK/PLLs in case of a wrong configuration
#[derive(Copy, Clone)]
pub struct RccConfig {
    /// The voltage range influences the maximum clock frequencies for different parts of the device
    ///
    /// In particular, system clocks exceeding 110 MHz require `RANGE1`, and system clocks exceeding
    /// 55 MHz require at least `RANGE2`
    ///
    /// See RM0456 § 10.5.4 for a general overview and § 11.4.10 for clock source frequency limits
    pub voltage_range: VoltageScale,

    // Base clock sources
    /// MSIS is generated by the MSI and can be selected as system clock
    ///
    /// - Configure as `None` to disable MSIS
    /// - Configure as `Some(MsiRange)` to enable MSIS with a specific frequency range
    pub msis: Option<MsiRange>,
    /// MSIK is generated by the MSI and can be selected by some peripherals as kernel clock
    ///
    /// - Configure as `None` to disable MSIK
    /// - Configure as `Some(MsiRange)` to enable MSIK with a specific frequency range
    pub msik: Option<MsiRange>,
    /// HSE can be generated from an external crystal/ceramic resonator or external clock
    ///
    /// - Configure as `None` to disable HSE
    /// - Configure as `Some(Hse)` to enable HSE with a specific frequency and mode
    pub hse: Option<Hse>,
    /// HSI48 is generated from an internal RC oscillator, fixed at 48 MHz (to be used for USB/RNG/SDMMC)
    ///
    /// - Configure as `false` to disable HSI48
    /// - Configure as `true` to enable HSI48
    pub hsi48: bool,
    /// LSI is a low-power clock source that can be kept running in Stop and Standby modes for the IWDG and RTC
    ///
    /// - Configure as `false` to disable LSI
    /// - Configure as `true` to enable LSI
    pub lsi: bool,

    // PLL
    /// PLL1 is generally used to provide clocks to the CPU and to some peripherals
    ///
    /// - Configure as `None` to disable PLL1
    /// - Configure as `Some(Pll)` to enable PLL1 with a specific configuration
    pub pll1: Option<Pll>,
    /// PLL2 is used to generate the kernel clock for peripherals
    ///
    /// - Configure as `None` to disable PLL2
    /// - Configure as `Some(Pll)` to enable PLL2 with a specific configuration
    pub pll2: Option<Pll>,
    /// PLL3 is used to generate the kernel clock for peripherals
    ///
    /// - Configure as `None` to disable PLL3
    /// - Configure as `Some(Pll)` to enable PLL3 with a specific configuration
    pub pll3: Option<Pll>,

    // SYSCLK, buses (see RM0456 § 11.4, Figure 38 for the clock tree)
    /// Selects which clock source drives the system clock
    ///
    /// Note: in case the selected source is not available (wasn't enabled/configured), `sys` will be overridden by `Sysclk::Hsi`,
    /// since HSI16 is always enabled
    pub sys: Sysclk,
    /// Selects a prescaler, to divide SYSCLK into HCLK
    ///
    /// Note: the `voltage_range` restricts the maximum value of HCLK
    /// - In case the resulting HCLK is too high, `ahb_pre` will be overridden by `AHBPrescaler::Div512`
    pub ahb_pre: AHBPrescaler,
    /// Selects a prescaler, to divide HCLK into PCLK1
    pub apb1_pre: APBPrescaler,
    /// Selects a prescaler, to divide HCLK into PCLK2
    pub apb2_pre: APBPrescaler,
    /// Selects a prescaler, to divide HCLK into PCLK3
    pub apb3_pre: APBPrescaler,

    // Peripheral kernel clock selection muxes
    /// Selects the clock source for each peripheral
    ///
    /// The default values of `ClockMuxConfig` represent the reset values of the corresponding registers
    pub mux: ClockMuxConfig,
}

/// Configuration for peripheral clock sources
#[derive(Copy, Clone, Default)]
pub struct ClockMuxConfig {
    pub rtcsel: Rtcsel,
    pub fdcan1sel: Fdcansel,
    pub i2c1sel: I2csel,
    pub i2c2sel: I2csel,
    pub i2c4sel: I2csel,
    pub iclksel: Iclksel,
    pub lptim2sel: Lptim2sel,
    pub spi1sel: Spi1sel,
    pub spi2sel: Spi2sel,
    pub uart4sel: Usartsel,
    pub uart5sel: Usartsel,
    pub usart1sel: Usart1sel,
    pub usart3sel: Usartsel,
    pub octospisel: Octospisel,
    pub rngsel: Rngsel,
    pub saessel: Saessel,
    pub sai1sel: Saisel,
    pub sdmmcsel: Sdmmcsel,
    pub adcdacsel: Adcdacsel,
    pub adf1sel: Adfsel,
    pub dac1sel: Dacsel,
    pub i2c3sel: I2c3sel,
    pub lptim1sel: Lptimsel,
    pub lpuart1sel: Lpusartsel,
    pub spi3sel: Spi3sel,
}
impl ClockMuxConfig {
    pub(crate) fn init(&self, rcc: &Rcc) {
        rcc.set_clock_sources(
            // BDCR
            self.rtcsel,
            // CCIPR1
            self.fdcan1sel,
            self.i2c1sel,
            self.i2c2sel,
            self.i2c4sel,
            self.iclksel,
            self.lptim2sel,
            self.spi1sel,
            self.spi2sel,
            self.uart4sel,
            self.uart5sel,
            self.usart1sel,
            self.usart3sel,
            // CCIPR2
            self.octospisel,
            self.rngsel,
            self.saessel,
            self.sai1sel,
            self.sdmmcsel,
            // CCIPR3
            self.adcdacsel,
            self.adf1sel,
            self.dac1sel,
            self.i2c3sel,
            self.lptim1sel,
            self.lpuart1sel,
            self.spi3sel,
        );
    }
}

#[derive(Copy, Clone)]
pub struct Hse {
    pub freq: Hertz,
    pub mode: HseMode,
}

#[derive(Copy, Clone)]
pub enum HseMode {
    /// Crystal/ceramic oscillator (HSEBYP=0)
    Oscillator,
    /// External analog clock (low swing) (HSEBYP=1, HSEEXT=0)
    Bypass,
    /// External digital clock (full swing) (HSEBYP=1, HSEEXT=1)
    BypassDigital,
}

#[derive(Clone, Copy)]
pub struct Pll {
    /// The clock source for the PLL.
    ///
    /// Note: in case the selected source is not available (wasn't enabled/configured), `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled)
    pub source: PllSource,
    /// The PLL pre-divider
    ///
    /// Note: `source` divided by `m` (the reference frequency) must be between 4 and 16 MHz
    /// - in case the resulting frequency is invalid (not between 4-16MHz), `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled)
    ///   and `prediv` by `PllPreDiv::Div4`, forcing the reference frequency to 4MHz
    pub prediv: PllPreDiv,
    /// The PLL multiplier.
    ///
    /// Note: the `voltage_range` restricts the maximum VCO frequency
    /// - in case the resulting frequency is invalid, `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled), `prediv` by `PllPreDiv::Div4`
    ///   and `mul` by `PllMul::Mul32`, forcing the VCO frequency to 128MHz
    pub mul: PllMul,
    /// The divider for the P output.
    ///
    /// The P output is one of several options that can be used to feed the SAI/MDF/ADF Clock mux's.
    ///
    /// Note: the `voltage_range` restricts the maximum output frequency
    /// - in case `divp` is not `None` and the resulting frequency is invalid, `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled),
    ///   `prediv` by `PllPreDiv::Div4`, `mul` by `PllMul::Mul32` and `divp` by `Some(PllDiv::Div4)`, forcing the output frequency to 32MHz
    pub divp: Option<PllDiv>,
    /// The divider for the Q output.
    ///
    /// The Q ouput is one of severals options that can be used to feed the 48MHz clocks
    /// and the OCTOSPI clock. It may also be used on the MDF/ADF clock mux's.
    ///
    /// Note: the `voltage_range` restricts the maximum output frequency
    /// - in case `divq` is not `None` and the resulting frequency is invalid, `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled),
    ///   `prediv` by `PllPreDiv::Div4`, `mul` by `PllMul::Mul32` and `divq` by `Some(PllDiv::Div4)`, forcing the output frequency to 32MHz
    pub divq: Option<PllDiv>,
    /// The divider for the R output.
    ///
    /// Note: the `voltage_range` restricts the maximum output frequency
    /// - in case `divr` is not `None` and the resulting frequency is invalid, `source` will be overridden by `PllSource::Hsi` (since HSI16 is always enabled),
    ///   `prediv` by `PllPreDiv::Div4`, `mul` by `PllMul::Mul32` and `divr` by `Some(PllDiv::Div4)`, forcing the output frequency to 32MHz
    pub divr: Option<PllDiv>,
}

pub struct PllInput {
    pub hsi16: Hertz,
    pub hse: Option<Hertz>,
    pub msi: Option<Hertz>,
}
