# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

# Makefile for building the tock kernel for a LiteX SoC targeting a
# Digilent Arty-A7 FPGA development board

TARGET=riscv32imc-unknown-none-elf
PLATFORM=litex_arty

include ../../Makefile.common

