#!/bin/bash

# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.
# Copyright Google LLC 2022.

echo Syntect should be able to recognize this as a Bash script, even though it \
     lacks an extension.
