# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2026.

[package]
name = "mps2-an386"
version.workspace = true
authors.workspace = true
build = "../../build.rs"
edition.workspace = true

[dependencies]
cortexm4 = { path = "../../../arch/cortex-m4" }
kernel = { path = "../../../kernel" }
qemu_arm_mps2 = { path = "../../../chips/qemu_arm_mps2" }
qemu_arm_mps2_an386 = { path = "../../../chips/qemu_arm_mps2_an386" }
mps2_base = { path = "../mps2_base" }

[build-dependencies]
tock_build_scripts = { path = "../../build_scripts" }

[lints]
workspace = true
