# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

include ../../Makefile.common
include ../../configurations/nrf52840dk/nrf52840dk.mk
