////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2025-12-04
//   /home/vic/Dev/Work/tockFULL/tock/tools/svd2regs/svd2regs.py --svd /home/vic/Dev/Work/tockFULL/tock/chips/stm32u5xx/STM32U545.svd ADC --group --save /home/vic/Dev/Work/tockFULL/tock/chips/stm32u5xx/src/adc_regs.rs

use kernel::utilities::StaticRef;
use kernel::utilities::registers::{self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly};
    
register_structs! {
    /// ADC1
    AdcRegisters {
        /// ADC interrupt and status register
        (0x000 => adc_isr: ReadWrite<u32, ADC_ISR::Register>),
        /// ADC interrupt enable register
        (0x004 => adc_ier: ReadWrite<u32, ADC_IER::Register>),
        /// ADC control register
        (0x008 => adc_cr: ReadWrite<u32, ADC_CR::Register>),
        /// ADC configuration register
        (0x00C => adc_cfgr1: ReadWrite<u32, ADC_CFGR1::Register>),
        /// ADC configuration register 2
        (0x010 => adc_cfgr2: ReadWrite<u32, ADC_CFGR2::Register>),
        /// ADC sample time register 1
        (0x014 => adc_smpr1: ReadWrite<u32, ADC_SMPR1::Register>),
        /// ADC sample time register 2
        (0x018 => adc_smpr2: ReadWrite<u32, ADC_SMPR2::Register>),
        /// ADC channel preselection register
        (0x01C => adc_pcsel: ReadWrite<u32, ADC_PCSEL::Register>),
        (0x020 => _reserved0),
        /// ADC regular sequence register 1
        (0x030 => adc_sqr1: ReadWrite<u32, ADC_SQR1::Register>),
        /// ADC regular sequence register 2
        (0x034 => adc_sqr2: ReadWrite<u32, ADC_SQR2::Register>),
        /// ADC regular sequence register 3
        (0x038 => adc_sqr3: ReadWrite<u32, ADC_SQR3::Register>),
        /// ADC regular sequence register 4
        (0x03C => adc_sqr4: ReadWrite<u32, ADC_SQR4::Register>),
        /// ADC regular Data Register
        (0x040 => adc_dr: ReadOnly<u32>),
        (0x044 => _reserved1),
        /// ADC injected sequence register
        (0x04C => adc_jsqr: ReadWrite<u32, ADC_JSQR::Register>),
        (0x050 => _reserved2),
        /// ADC offset register
        (0x060 => adc_ofr1: ReadWrite<u32, ADC_OFR1::Register>),
        /// ADC offset register
        (0x064 => adc_ofr2: ReadWrite<u32, ADC_OFR2::Register>),
        /// ADC offset register
        (0x068 => adc_ofr3: ReadWrite<u32, ADC_OFR3::Register>),
        /// ADC offset register
        (0x06C => adc_ofr4: ReadWrite<u32, ADC_OFR4::Register>),
        /// ADC gain compensation register
        (0x070 => adc_gcomp: ReadWrite<u32, ADC_GCOMP::Register>),
        (0x074 => _reserved3),
        /// ADC injected data register
        (0x080 => adc_jdr1: ReadOnly<u32>),
        /// ADC injected data register
        (0x084 => adc_jdr2: ReadOnly<u32>),
        /// ADC injected data register
        (0x088 => adc_jdr3: ReadOnly<u32>),
        /// ADC injected data register
        (0x08C => adc_jdr4: ReadOnly<u32>),
        (0x090 => _reserved4),
        /// ADC analog watchdog 2 configuration register
        (0x0A0 => adc_awd2cr: ReadWrite<u32>),
        /// ADC analog watchdog 3 configuration register
        (0x0A4 => adc_awd3cr: ReadWrite<u32>),
        /// ADC watchdog threshold register 1
        (0x0A8 => adc_ltr1: ReadWrite<u32>),
        /// ADC watchdog threshold register 1
        (0x0AC => adc_htr1: ReadWrite<u32, ADC_HTR1::Register>),
        /// ADC watchdog lower threshold register 2
        (0x0B0 => adc_ltr2: ReadWrite<u32>),
        /// ADC watchdog higher threshold register 2
        (0x0B4 => adc_htr2: ReadWrite<u32>),
        /// ADC watchdog lower threshold register 3
        (0x0B8 => adc_ltr3: ReadWrite<u32>),
        /// ADC watchdog higher threshold register 3
        (0x0BC => adc_htr3: ReadWrite<u32>),
        /// ADC differential mode selection register
        (0x0C0 => adc_difsel: ReadWrite<u32>),
        /// ADC user control register
        (0x0C4 => adc_calfact: ReadWrite<u32, ADC_CALFACT::Register>),
        /// ADC calibration factor register
        (0x0C8 => adc_calfact2: ReadWrite<u32>),
        (0x0CC => @END),
    }
}
register_bitfields![u32,
ADC_ISR [
    /// LDORDY
    LDORDY OFFSET(12) NUMBITS(1) [],
    /// AWD3
    AWD3 OFFSET(9) NUMBITS(1) [],
    /// AWD2
    AWD2 OFFSET(8) NUMBITS(1) [],
    /// AWD1
    AWD1 OFFSET(7) NUMBITS(1) [],
    /// JEOS
    JEOS OFFSET(6) NUMBITS(1) [],
    /// JEOC
    JEOC OFFSET(5) NUMBITS(1) [],
    /// OVR
    OVR OFFSET(4) NUMBITS(1) [],
    /// EOS
    EOS OFFSET(3) NUMBITS(1) [],
    /// EOC
    EOC OFFSET(2) NUMBITS(1) [],
    /// EOSMP
    EOSMP OFFSET(1) NUMBITS(1) [],
    /// ADRDY
    ADRDY OFFSET(0) NUMBITS(1) []
],
ADC_IER [
    /// AWD3IE
    AWD3IE OFFSET(9) NUMBITS(1) [],
    /// AWD2IE
    AWD2IE OFFSET(8) NUMBITS(1) [],
    /// AWD1IE
    AWD1IE OFFSET(7) NUMBITS(1) [],
    /// JEOSIE
    JEOSIE OFFSET(6) NUMBITS(1) [],
    /// JEOCIE
    JEOCIE OFFSET(5) NUMBITS(1) [],
    /// OVRIE
    OVRIE OFFSET(4) NUMBITS(1) [],
    /// EOSIE
    EOSIE OFFSET(3) NUMBITS(1) [],
    /// EOCIE
    EOCIE OFFSET(2) NUMBITS(1) [],
    /// EOSMPIE
    EOSMPIE OFFSET(1) NUMBITS(1) [],
    /// ADRDYIE
    ADRDYIE OFFSET(0) NUMBITS(1) []
],
ADC_CR [
    /// ADCAL
    ADCAL OFFSET(31) NUMBITS(1) [],
    /// DEEPPWD
    DEEPPWD OFFSET(29) NUMBITS(1) [],
    /// ADVREGEN
    ADVREGEN OFFSET(28) NUMBITS(1) [],
    /// CALINDEX
    CALINDEX OFFSET(24) NUMBITS(4) [],
    /// ADCALLIN
    ADCALLIN OFFSET(16) NUMBITS(1) [],
    /// JADSTP
    JADSTP OFFSET(5) NUMBITS(1) [],
    /// ADSTP
    ADSTP OFFSET(4) NUMBITS(1) [],
    /// JADSTART
    JADSTART OFFSET(3) NUMBITS(1) [],
    /// ADSTART
    ADSTART OFFSET(2) NUMBITS(1) [],
    /// ADDIS
    ADDIS OFFSET(1) NUMBITS(1) [],
    /// ADEN
    ADEN OFFSET(0) NUMBITS(1) []
],
ADC_CFGR1 [
    /// AWD1CH
    AWD1CH OFFSET(26) NUMBITS(5) [],
    /// JAUTO
    JAUTO OFFSET(25) NUMBITS(1) [],
    /// JAWD1EN
    JAWD1EN OFFSET(24) NUMBITS(1) [],
    /// AWD1EN
    AWD1EN OFFSET(23) NUMBITS(1) [],
    /// AWD1SGL
    AWD1SGL OFFSET(22) NUMBITS(1) [],
    /// JDISCEN
    JDISCEN OFFSET(20) NUMBITS(1) [],
    /// DISCNUM
    DISCNUM OFFSET(17) NUMBITS(3) [],
    /// DISCEN
    DISCEN OFFSET(16) NUMBITS(1) [],
    /// AUTDLY
    AUTDLY OFFSET(14) NUMBITS(1) [],
    /// CONT
    CONT OFFSET(13) NUMBITS(1) [],
    /// OVRMOD
    OVRMOD OFFSET(12) NUMBITS(1) [],
    /// EXTEN
    EXTEN OFFSET(10) NUMBITS(2) [],
    /// EXTSEL
    EXTSEL OFFSET(5) NUMBITS(5) [],
    /// RES
    RES OFFSET(2) NUMBITS(2) [],
    /// DMNGT
    DMNGT OFFSET(0) NUMBITS(2) []
],
ADC_CFGR2 [
    /// LSHIFT
    LSHIFT OFFSET(28) NUMBITS(4) [],
    /// LFTRIG
    LFTRIG OFFSET(27) NUMBITS(1) [],
    /// OSR
    OSR OFFSET(16) NUMBITS(10) [],
    /// SMPTRIG
    SMPTRIG OFFSET(15) NUMBITS(1) [],
    /// SWTRIG
    SWTRIG OFFSET(14) NUMBITS(1) [],
    /// BULB
    BULB OFFSET(13) NUMBITS(1) [],
    /// ROVSM
    ROVSM OFFSET(10) NUMBITS(1) [],
    /// TROVS
    TROVS OFFSET(9) NUMBITS(1) [],
    /// OVSS
    OVSS OFFSET(5) NUMBITS(4) [],
    /// JOVSE
    JOVSE OFFSET(1) NUMBITS(1) [],
    /// ROVSE
    ROVSE OFFSET(0) NUMBITS(1) []
],
ADC_SMPR1 [
    /// SMP9
    SMP9 OFFSET(27) NUMBITS(3) [],
    /// SMP8
    SMP8 OFFSET(24) NUMBITS(3) [],
    /// SMP7
    SMP7 OFFSET(21) NUMBITS(3) [],
    /// SMP6
    SMP6 OFFSET(18) NUMBITS(3) [],
    /// SMP5
    SMP5 OFFSET(15) NUMBITS(3) [],
    /// SMP4
    SMP4 OFFSET(12) NUMBITS(3) [],
    /// SMP3
    SMP3 OFFSET(9) NUMBITS(3) [],
    /// SMP2
    SMP2 OFFSET(6) NUMBITS(3) [],
    /// SMP1
    SMP1 OFFSET(3) NUMBITS(3) [],
    /// SMP0
    SMP0 OFFSET(0) NUMBITS(3) []
],
ADC_SMPR2 [
    /// SMP19
    SMP19 OFFSET(27) NUMBITS(3) [],
    /// SMP18
    SMP18 OFFSET(24) NUMBITS(3) [],
    /// SMP17
    SMP17 OFFSET(21) NUMBITS(3) [],
    /// SMP16
    SMP16 OFFSET(18) NUMBITS(3) [],
    /// SMP15
    SMP15 OFFSET(15) NUMBITS(3) [],
    /// SMP14
    SMP14 OFFSET(12) NUMBITS(3) [],
    /// SMP13
    SMP13 OFFSET(9) NUMBITS(3) [],
    /// SMP12
    SMP12 OFFSET(6) NUMBITS(3) [],
    /// SMP11
    SMP11 OFFSET(3) NUMBITS(3) [],
    /// SMP10
    SMP10 OFFSET(0) NUMBITS(3) []
],
ADC_PCSEL [
    /// PCSEL19
    PCSEL19 OFFSET(19) NUMBITS(1) [],
    /// PCSEL18
    PCSEL18 OFFSET(18) NUMBITS(1) [],
    /// PCSEL17
    PCSEL17 OFFSET(17) NUMBITS(1) [],
    /// PCSEL16
    PCSEL16 OFFSET(16) NUMBITS(1) [],
    /// PCSEL15
    PCSEL15 OFFSET(15) NUMBITS(1) [],
    /// PCSEL14
    PCSEL14 OFFSET(14) NUMBITS(1) [],
    /// PCSEL13
    PCSEL13 OFFSET(13) NUMBITS(1) [],
    /// PCSEL12
    PCSEL12 OFFSET(12) NUMBITS(1) [],
    /// PCSEL11
    PCSEL11 OFFSET(11) NUMBITS(1) [],
    /// PCSEL10
    PCSEL10 OFFSET(10) NUMBITS(1) [],
    /// PCSEL9
    PCSEL9 OFFSET(9) NUMBITS(1) [],
    /// PCSEL8
    PCSEL8 OFFSET(8) NUMBITS(1) [],
    /// PCSEL7
    PCSEL7 OFFSET(7) NUMBITS(1) [],
    /// PCSEL6
    PCSEL6 OFFSET(6) NUMBITS(1) [],
    /// PCSEL5
    PCSEL5 OFFSET(5) NUMBITS(1) [],
    /// PCSEL4
    PCSEL4 OFFSET(4) NUMBITS(1) [],
    /// PCSEL3
    PCSEL3 OFFSET(3) NUMBITS(1) [],
    /// PCSEL2
    PCSEL2 OFFSET(2) NUMBITS(1) [],
    /// PCSEL1
    PCSEL1 OFFSET(1) NUMBITS(1) [],
    /// PCSEL0
    PCSEL0 OFFSET(0) NUMBITS(1) []
],
ADC_SQR1 [
    /// SQ4
    SQ4 OFFSET(24) NUMBITS(5) [],
    /// SQ3
    SQ3 OFFSET(18) NUMBITS(5) [],
    /// SQ2
    SQ2 OFFSET(12) NUMBITS(5) [],
    /// SQ1
    SQ1 OFFSET(6) NUMBITS(5) [],
    /// L
    L OFFSET(0) NUMBITS(4) []
],
ADC_SQR2 [
    /// SQ9
    SQ9 OFFSET(24) NUMBITS(5) [],
    /// SQ8
    SQ8 OFFSET(18) NUMBITS(5) [],
    /// SQ7
    SQ7 OFFSET(12) NUMBITS(5) [],
    /// SQ6
    SQ6 OFFSET(6) NUMBITS(5) [],
    /// SQ5
    SQ5 OFFSET(0) NUMBITS(5) []
],
ADC_SQR3 [
    /// SQ14
    SQ14 OFFSET(24) NUMBITS(5) [],
    /// SQ13
    SQ13 OFFSET(18) NUMBITS(5) [],
    /// SQ12
    SQ12 OFFSET(12) NUMBITS(5) [],
    /// SQ11
    SQ11 OFFSET(6) NUMBITS(5) [],
    /// SQ10
    SQ10 OFFSET(0) NUMBITS(5) []
],
ADC_SQR4 [
    /// SQ16
    SQ16 OFFSET(6) NUMBITS(5) [],
    /// SQ15
    SQ15 OFFSET(0) NUMBITS(5) []
],
ADC_DR [
    /// RDATA
    RDATA OFFSET(0) NUMBITS(32) []
],
ADC_JSQR [
    /// JSQ4
    JSQ4 OFFSET(27) NUMBITS(5) [],
    /// JSQ3
    JSQ3 OFFSET(21) NUMBITS(5) [],
    /// JSQ2
    JSQ2 OFFSET(15) NUMBITS(5) [],
    /// JSQ1
    JSQ1 OFFSET(9) NUMBITS(5) [],
    /// JEXTEN
    JEXTEN OFFSET(7) NUMBITS(2) [],
    /// JEXTSEL
    JEXTSEL OFFSET(2) NUMBITS(5) [],
    /// JL
    JL OFFSET(0) NUMBITS(2) []
],
ADC_OFR1 [
    /// OFFSET_CH
    OFFSET_CH OFFSET(27) NUMBITS(5) [],
    /// SSAT
    SSAT OFFSET(26) NUMBITS(1) [],
    /// USAT
    USAT OFFSET(25) NUMBITS(1) [],
    /// POSOFF
    POSOFF OFFSET(24) NUMBITS(1) [],
    /// OFFSET
    OFFSET OFFSET(0) NUMBITS(24) []
],
ADC_OFR2 [
    /// OFFSET_CH
    OFFSET_CH OFFSET(27) NUMBITS(5) [],
    /// SSAT
    SSAT OFFSET(26) NUMBITS(1) [],
    /// USAT
    USAT OFFSET(25) NUMBITS(1) [],
    /// POSOFF
    POSOFF OFFSET(24) NUMBITS(1) [],
    /// OFFSET
    OFFSET OFFSET(0) NUMBITS(24) []
],
ADC_OFR3 [
    /// OFFSET_CH
    OFFSET_CH OFFSET(27) NUMBITS(5) [],
    /// SSAT
    SSAT OFFSET(26) NUMBITS(1) [],
    /// USAT
    USAT OFFSET(25) NUMBITS(1) [],
    /// POSOFF
    POSOFF OFFSET(24) NUMBITS(1) [],
    /// OFFSET
    OFFSET OFFSET(0) NUMBITS(24) []
],
ADC_OFR4 [
    /// OFFSET_CH
    OFFSET_CH OFFSET(27) NUMBITS(5) [],
    /// SSAT
    SSAT OFFSET(26) NUMBITS(1) [],
    /// USAT
    USAT OFFSET(25) NUMBITS(1) [],
    /// POSOFF
    POSOFF OFFSET(24) NUMBITS(1) [],
    /// OFFSET
    OFFSET OFFSET(0) NUMBITS(24) []
],
ADC_GCOMP [
    /// GCOMP
    GCOMP OFFSET(31) NUMBITS(1) [],
    /// GCOMPCOEFF
    GCOMPCOEFF OFFSET(0) NUMBITS(14) []
],
ADC_JDR1 [
    /// JDATA
    JDATA OFFSET(0) NUMBITS(32) []
],
ADC_JDR2 [
    /// JDATA
    JDATA OFFSET(0) NUMBITS(32) []
],
ADC_JDR3 [
    /// JDATA
    JDATA OFFSET(0) NUMBITS(32) []
],
ADC_JDR4 [
    /// JDATA
    JDATA OFFSET(0) NUMBITS(32) []
],
ADC_AWD2CR [
    /// AWD2CH
    AWD2CH OFFSET(0) NUMBITS(20) []
],
ADC_AWD3CR [
    /// AWD3CH
    AWD3CH OFFSET(0) NUMBITS(20) []
],
ADC_LTR1 [
    /// LTR1
    LTR1 OFFSET(0) NUMBITS(25) []
],
ADC_HTR1 [
    /// AWDFILT1
    AWDFILT1 OFFSET(29) NUMBITS(3) [],
    /// HTR1
    HTR1 OFFSET(0) NUMBITS(25) []
],
ADC_LTR2 [
    /// LTR2
    LTR2 OFFSET(0) NUMBITS(25) []
],
ADC_HTR2 [
    /// HTR2
    HTR2 OFFSET(0) NUMBITS(25) []
],
ADC_LTR3 [
    /// LTR3
    LTR3 OFFSET(0) NUMBITS(25) []
],
ADC_HTR3 [
    /// HTR3
    HTR3 OFFSET(0) NUMBITS(25) []
],
ADC_DIFSEL [
    /// DIFSEL
    DIFSEL OFFSET(0) NUMBITS(20) []
],
ADC_CALFACT [
    /// CAPTURE_COEF
    CAPTURE_COEF OFFSET(25) NUMBITS(1) [],
    /// LATCH_COEF
    LATCH_COEF OFFSET(24) NUMBITS(1) [],
    /// VALIDITY
    VALIDITY OFFSET(16) NUMBITS(1) [],
    /// I_APB_DATA
    I_APB_DATA OFFSET(8) NUMBITS(8) [],
    /// I_APB_ADDR
    I_APB_ADDR OFFSET(0) NUMBITS(8) []
],
ADC_CALFACT2 [
    /// CALFACT
    CALFACT OFFSET(0) NUMBITS(32) []
]
];
const ADC1_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x42028000 as *const AdcRegisters) };


const SEC_ADC1_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x52028000 as *const AdcRegisters) };


const ADC12_Common_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x42028300 as *const AdcRegisters) };


const SEC_ADC12_Common_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x52028300 as *const AdcRegisters) };


const ADC4_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x46021000 as *const AdcRegisters) };


const SEC_ADC4_BASE: StaticRef<AdcRegisters> =
    unsafe { StaticRef::new(0x56021000 as *const AdcRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

