# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2026.

[package]
name = "unsafe-requirements"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
ignore = "0.4"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
