# Makefile for building the tock kernel for the host testing

TARGET=x86_64-unknown-linux-gnu
PLATFORM=host_emulation

# Use std x86_64 rust flags, overriding Makefile.common
RUSTC_FLAGS :=

include ../Makefile.common
