# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

include = [
  "../../cargo/tock_flags.toml",
  "../../cargo/unstable_flags.toml",
]

[build]
target = "i486-unknown-none.json"

# Required for .json target
[unstable]
json-target-spec = true

[target.i486-unknown-none]
runner = "qemu-system-i386 -cpu 486 -machine q35 -net none -device isa-debug-exit,iobase=0xf4,iosize=0x04 -device virtio-rng-pci,disable-legacy=on -serial stdio -kernel"
