////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2025-12-08
//   /home/vic/Dev/Work/tockFULL/tock/tools/svd2regs/svd2regs.py --svd /home/vic/Dev/Work/tockFULL/tock/chips/stm32u5xx/STM32U545.svd USART --group --save /home/vic/Dev/Work/tockFULL/tock/chips/stm32u5xx/src/usart_regs.rs

use kernel::utilities::StaticRef;
use kernel::utilities::registers::{self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly};
    
register_structs! {
    /// Universal synchronous asynchronous receiver
///       transmitter
    UsartRegisters {
        /// Control register 1
        (0x000 => cr1_enabled: ReadWrite<u32, CR1_enabled::Register>),
        /// Control register 2
        (0x004 => cr2: ReadWrite<u32, CR2::Register>),
        /// Control register 3
        (0x008 => cr3: ReadWrite<u32, CR3::Register>),
        /// Baud rate register
        (0x00C => brr: ReadWrite<u32>),
        /// Guard time and prescaler
///           register
        (0x010 => gtpr: ReadWrite<u32, GTPR::Register>),
        /// Receiver timeout register
        (0x014 => rtor: ReadWrite<u32, RTOR::Register>),
        /// Request register
        (0x018 => rqr: WriteOnly<u32, RQR::Register>),
        /// Interrupt & status
///           register
        (0x01C => isr_enabled: ReadOnly<u32, ISR_enabled::Register>),
        /// Interrupt flag clear register
        (0x020 => icr: WriteOnly<u32, ICR::Register>),
        /// Receive data register
        (0x024 => rdr: ReadOnly<u32>),
        /// Transmit data register
        (0x028 => tdr: ReadWrite<u32>),
        /// PRESC
        (0x02C => presc: ReadWrite<u32>),
        /// AUTOCR
        (0x030 => autocr: ReadWrite<u32, AUTOCR::Register>),
        (0x034 => @END),
    }
}
register_bitfields![u32,
CR1_enabled [
    /// Word length
    M1 OFFSET(28) NUMBITS(1) [],
    /// End of Block interruptenable
    EOBIE OFFSET(27) NUMBITS(1) [],
    /// Receiver timeout interrupt
    RTOIE OFFSET(26) NUMBITS(1) [],
    /// DEAT
    DEAT OFFSET(21) NUMBITS(5) [],
    /// DEDT
    DEDT OFFSET(16) NUMBITS(5) [],
    /// Oversampling mode
    OVER8 OFFSET(15) NUMBITS(1) [],
    /// Character match interrupt
///               enable
    CMIE OFFSET(14) NUMBITS(1) [],
    /// Mute mode enable
    MME OFFSET(13) NUMBITS(1) [],
    /// Word length
    M0 OFFSET(12) NUMBITS(1) [],
    /// Receiver wakeup method
    WAKE OFFSET(11) NUMBITS(1) [],
    /// Parity control enable
    PCE OFFSET(10) NUMBITS(1) [],
    /// Parity selection
    PS OFFSET(9) NUMBITS(1) [],
    /// PE interrupt enable
    PEIE OFFSET(8) NUMBITS(1) [],
    /// TXFIFO not full interrupt enable
    TXFNFIE OFFSET(7) NUMBITS(1) [],
    /// Transmission complete interrupt
///               enable
    TCIE OFFSET(6) NUMBITS(1) [],
    /// RXFIFO not empty interrupt enable
    RXFNEIE OFFSET(5) NUMBITS(1) [],
    /// IDLE interrupt enable
    IDLEIE OFFSET(4) NUMBITS(1) [],
    /// Transmitter enable
    TE OFFSET(3) NUMBITS(1) [],
    /// Receiver enable
    RE OFFSET(2) NUMBITS(1) [],
    /// USART enable in Stop mode
    UESM OFFSET(1) NUMBITS(1) [],
    /// USART enable
    UE OFFSET(0) NUMBITS(1) [],
    /// FIFOEN
    FIFOEN OFFSET(29) NUMBITS(1) [],
    /// TXFEIE
    TXFEIE OFFSET(30) NUMBITS(1) [],
    /// RXFFIE
    RXFFIE OFFSET(31) NUMBITS(1) []
],
CR1_disabled [
    /// Word length
    M1 OFFSET(28) NUMBITS(1) [],
    /// End of Block interrupt
///               enable
    EOBIE OFFSET(27) NUMBITS(1) [],
    /// Receiver timeout interrupt
///               enable
    RTOIE OFFSET(26) NUMBITS(1) [],
    /// DEAT
    DEAT OFFSET(21) NUMBITS(5) [],
    /// DEDT
    DEDT OFFSET(16) NUMBITS(5) [],
    /// Oversampling mode
    OVER8 OFFSET(15) NUMBITS(1) [],
    /// Character match interrupt
///               enable
    CMIE OFFSET(14) NUMBITS(1) [],
    /// Mute mode enable
    MME OFFSET(13) NUMBITS(1) [],
    /// Word length
    M0 OFFSET(12) NUMBITS(1) [],
    /// Receiver wakeup method
    WAKE OFFSET(11) NUMBITS(1) [],
    /// Parity control enable
    PCE OFFSET(10) NUMBITS(1) [],
    /// Parity selection
    PS OFFSET(9) NUMBITS(1) [],
    /// PE interrupt enable
    PEIE OFFSET(8) NUMBITS(1) [],
    /// TXFIFO not full interrupt enable
    TXFNFIE OFFSET(7) NUMBITS(1) [],
    /// Transmission complete interrupt
///               enable
    TCIE OFFSET(6) NUMBITS(1) [],
    /// RXFIFO not empty interrupt enable
    RXFNEIE OFFSET(5) NUMBITS(1) [],
    /// IDLE interrupt enable
    IDLEIE OFFSET(4) NUMBITS(1) [],
    /// Transmitter enable
    TE OFFSET(3) NUMBITS(1) [],
    /// Receiver enable
    RE OFFSET(2) NUMBITS(1) [],
    /// USART enable in Stop mode
    UESM OFFSET(1) NUMBITS(1) [],
    /// USART enable
    UE OFFSET(0) NUMBITS(1) [],
    /// FIFOEN
    FIFOEN OFFSET(29) NUMBITS(1) []
],
CR2 [
    /// Address of the USART node
    ADD OFFSET(24) NUMBITS(8) [],
    /// Receiver timeout enable
    RTOEN OFFSET(23) NUMBITS(1) [],
    /// Auto baud rate mode
    ABRMOD OFFSET(21) NUMBITS(2) [],
    /// Auto baud rate enable
    ABREN OFFSET(20) NUMBITS(1) [],
    /// Most significant bit first
    MSBFIRST OFFSET(19) NUMBITS(1) [],
    /// Binary data inversion
    DATAINV OFFSET(18) NUMBITS(1) [],
    /// TX pin active level
///               inversion
    TXINV OFFSET(17) NUMBITS(1) [],
    /// RX pin active level
///               inversion
    RXINV OFFSET(16) NUMBITS(1) [],
    /// Swap TX/RX pins
    SWAP OFFSET(15) NUMBITS(1) [],
    /// LIN mode enable
    LINEN OFFSET(14) NUMBITS(1) [],
    /// STOP bits
    STOP OFFSET(12) NUMBITS(2) [],
    /// Clock enable
    CLKEN OFFSET(11) NUMBITS(1) [],
    /// Clock polarity
    CPOL OFFSET(10) NUMBITS(1) [],
    /// Clock phase
    CPHA OFFSET(9) NUMBITS(1) [],
    /// Last bit clock pulse
    LBCL OFFSET(8) NUMBITS(1) [],
    /// LIN break detection interrupt
///               enable
    LBDIE OFFSET(6) NUMBITS(1) [],
    /// LIN break detection length
    LBDL OFFSET(5) NUMBITS(1) [],
    /// 7-bit Address Detection/4-bit Address
///               Detection
    ADDM7 OFFSET(4) NUMBITS(1) [],
    /// SLVEN
    SLVEN OFFSET(0) NUMBITS(1) [],
    /// DIS_NSS
    DIS_NSS OFFSET(3) NUMBITS(1) []
],
CR3 [
    /// Smartcard auto-retry count
    SCARCNT OFFSET(17) NUMBITS(3) [],
    /// Driver enable polarity
///               selection
    DEP OFFSET(15) NUMBITS(1) [],
    /// Driver enable mode
    DEM OFFSET(14) NUMBITS(1) [],
    /// DMA Disable on Reception
///               Error
    DDRE OFFSET(13) NUMBITS(1) [],
    /// Overrun Disable
    OVRDIS OFFSET(12) NUMBITS(1) [],
    /// One sample bit method
///               enable
    ONEBIT OFFSET(11) NUMBITS(1) [],
    /// CTS interrupt enable
    CTSIE OFFSET(10) NUMBITS(1) [],
    /// CTS enable
    CTSE OFFSET(9) NUMBITS(1) [],
    /// RTS enable
    RTSE OFFSET(8) NUMBITS(1) [],
    /// DMA enable transmitter
    DMAT OFFSET(7) NUMBITS(1) [],
    /// DMA enable receiver
    DMAR OFFSET(6) NUMBITS(1) [],
    /// Smartcard mode enable
    SCEN OFFSET(5) NUMBITS(1) [],
    /// Smartcard NACK enable
    NACK OFFSET(4) NUMBITS(1) [],
    /// Half-duplex selection
    HDSEL OFFSET(3) NUMBITS(1) [],
    /// Ir low-power
    IRLP OFFSET(2) NUMBITS(1) [],
    /// Ir mode enable
    IREN OFFSET(1) NUMBITS(1) [],
    /// Error interrupt enable
    EIE OFFSET(0) NUMBITS(1) [],
    /// TXFTIE
    TXFTIE OFFSET(23) NUMBITS(1) [],
    /// TCBGTIE
    TCBGTIE OFFSET(24) NUMBITS(1) [],
    /// RXFTCFG
    RXFTCFG OFFSET(25) NUMBITS(3) [],
    /// RXFTIE
    RXFTIE OFFSET(28) NUMBITS(1) [],
    /// TXFTCFG
    TXFTCFG OFFSET(29) NUMBITS(3) []
],
BRR [
    /// BRR
    BRR OFFSET(0) NUMBITS(16) []
],
GTPR [
    /// Guard time value
    GT OFFSET(8) NUMBITS(8) [],
    /// Prescaler value
    PSC OFFSET(0) NUMBITS(8) []
],
RTOR [
    /// Block Length
    BLEN OFFSET(24) NUMBITS(8) [],
    /// Receiver timeout value
    RTO OFFSET(0) NUMBITS(24) []
],
RQR [
    /// Transmit data flush
///               request
    TXFRQ OFFSET(4) NUMBITS(1) [],
    /// Receive data flush request
    RXFRQ OFFSET(3) NUMBITS(1) [],
    /// Mute mode request
    MMRQ OFFSET(2) NUMBITS(1) [],
    /// Send break request
    SBKRQ OFFSET(1) NUMBITS(1) [],
    /// Auto baud rate request
    ABRRQ OFFSET(0) NUMBITS(1) []
],
ISR_enabled [
    /// REACK
    REACK OFFSET(22) NUMBITS(1) [],
    /// TEACK
    TEACK OFFSET(21) NUMBITS(1) [],
    /// RWU
    RWU OFFSET(19) NUMBITS(1) [],
    /// SBKF
    SBKF OFFSET(18) NUMBITS(1) [],
    /// CMF
    CMF OFFSET(17) NUMBITS(1) [],
    /// BUSY
    BUSY OFFSET(16) NUMBITS(1) [],
    /// ABRF
    ABRF OFFSET(15) NUMBITS(1) [],
    /// ABRE
    ABRE OFFSET(14) NUMBITS(1) [],
    /// EOBF
    EOBF OFFSET(12) NUMBITS(1) [],
    /// RTOF
    RTOF OFFSET(11) NUMBITS(1) [],
    /// CTS
    CTS OFFSET(10) NUMBITS(1) [],
    /// CTSIF
    CTSIF OFFSET(9) NUMBITS(1) [],
    /// LBDF
    LBDF OFFSET(8) NUMBITS(1) [],
    /// TXFNF
    TXFNF OFFSET(7) NUMBITS(1) [],
    /// TC
    TC OFFSET(6) NUMBITS(1) [],
    /// RXFNE
    RXFNE OFFSET(5) NUMBITS(1) [],
    /// IDLE
    IDLE OFFSET(4) NUMBITS(1) [],
    /// ORE
    ORE OFFSET(3) NUMBITS(1) [],
    /// NE
    NE OFFSET(2) NUMBITS(1) [],
    /// FE
    FE OFFSET(1) NUMBITS(1) [],
    /// PE
    PE OFFSET(0) NUMBITS(1) [],
    /// TXFE
    TXFE OFFSET(23) NUMBITS(1) [],
    /// RXFF
    RXFF OFFSET(24) NUMBITS(1) [],
    /// TCBGT
    TCBGT OFFSET(25) NUMBITS(1) [],
    /// RXFT
    RXFT OFFSET(26) NUMBITS(1) [],
    /// TXFT
    TXFT OFFSET(27) NUMBITS(1) []
],
ISR_disabled [
    /// REACK
    REACK OFFSET(22) NUMBITS(1) [],
    /// TEACK
    TEACK OFFSET(21) NUMBITS(1) [],
    /// RWU
    RWU OFFSET(19) NUMBITS(1) [],
    /// SBKF
    SBKF OFFSET(18) NUMBITS(1) [],
    /// CMF
    CMF OFFSET(17) NUMBITS(1) [],
    /// BUSY
    BUSY OFFSET(16) NUMBITS(1) [],
    /// ABRF
    ABRF OFFSET(15) NUMBITS(1) [],
    /// ABRE
    ABRE OFFSET(14) NUMBITS(1) [],
    /// UDR
    UDR OFFSET(13) NUMBITS(1) [],
    /// EOBF
    EOBF OFFSET(12) NUMBITS(1) [],
    /// RTOF
    RTOF OFFSET(11) NUMBITS(1) [],
    /// CTS
    CTS OFFSET(10) NUMBITS(1) [],
    /// CTSIF
    CTSIF OFFSET(9) NUMBITS(1) [],
    /// LBDF
    LBDF OFFSET(8) NUMBITS(1) [],
    /// TXFNF
    TXFNF OFFSET(7) NUMBITS(1) [],
    /// TC
    TC OFFSET(6) NUMBITS(1) [],
    /// RXFNE
    RXFNE OFFSET(5) NUMBITS(1) [],
    /// IDLE
    IDLE OFFSET(4) NUMBITS(1) [],
    /// ORE
    ORE OFFSET(3) NUMBITS(1) [],
    /// NE
    NE OFFSET(2) NUMBITS(1) [],
    /// FE
    FE OFFSET(1) NUMBITS(1) [],
    /// PE
    PE OFFSET(0) NUMBITS(1) [],
    /// TCBGT
    TCBGT OFFSET(25) NUMBITS(1) []
],
ICR [
    /// Character match clear flag
    CMCF OFFSET(17) NUMBITS(1) [],
    /// End of block clear flag
    EOBCF OFFSET(12) NUMBITS(1) [],
    /// Receiver timeout clear
///               flag
    RTOCF OFFSET(11) NUMBITS(1) [],
    /// CTS clear flag
    CTSCF OFFSET(9) NUMBITS(1) [],
    /// LIN break detection clear
///               flag
    LBDCF OFFSET(8) NUMBITS(1) [],
    /// Transmission complete clear
///               flag
    TCCF OFFSET(6) NUMBITS(1) [],
    /// Idle line detected clear
///               flag
    IDLECF OFFSET(4) NUMBITS(1) [],
    /// Overrun error clear flag
    ORECF OFFSET(3) NUMBITS(1) [],
    /// Noise detected clear flag
    NECF OFFSET(2) NUMBITS(1) [],
    /// Framing error clear flag
    FECF OFFSET(1) NUMBITS(1) [],
    /// Parity error clear flag
    PECF OFFSET(0) NUMBITS(1) [],
    /// TXFECF
    TXFECF OFFSET(5) NUMBITS(1) [],
    /// TCBGTCF
    TCBGTCF OFFSET(7) NUMBITS(1) [],
    /// UDRCF
    UDRCF OFFSET(13) NUMBITS(1) []
],
RDR [
    /// Receive data value
    RDR OFFSET(0) NUMBITS(9) []
],
TDR [
    /// Transmit data value
    TDR OFFSET(0) NUMBITS(9) []
],
PRESC [
    /// PRESCALER
    PRESCALER OFFSET(0) NUMBITS(4) []
],
AUTOCR [
    /// TECLREN
    TECLREN OFFSET(31) NUMBITS(1) [],
    /// IDLEDIS
    IDLEDIS OFFSET(18) NUMBITS(1) [],
    /// TRIGSEL
    TRIGSEL OFFSET(19) NUMBITS(4) [],
    /// TRIGEN
    TRIGEN OFFSET(17) NUMBITS(1) [],
    /// TRIPOL
    TRIGPOL OFFSET(16) NUMBITS(1) [],
    /// TDN
    TDN OFFSET(0) NUMBITS(16) []
]
];
const USART1_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x40013800 as *const UsartRegisters) };


const SEC_USART1_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x50013800 as *const UsartRegisters) };


const USART3_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x40004800 as *const UsartRegisters) };


const SEC_USART3_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x50004800 as *const UsartRegisters) };


const UART4_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x40004C00 as *const UsartRegisters) };


const SEC_UART4_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x50004C00 as *const UsartRegisters) };


const UART5_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x40005000 as *const UsartRegisters) };


const SEC_UART5_BASE: StaticRef<UsartRegisters> =
    unsafe { StaticRef::new(0x50005000 as *const UsartRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

