include src/apps/Makefile.mk
include src/chips/Makefile.mk
include src/common/Makefile.mk
include src/arch/$(ARCH)/Makefile.mk
include src/drivers/Makefile.mk
include src/hil/Makefile.mk
include src/platform/Makefile.mk
include src/process/Makefile.mk
include src/main/Makefile.mk
