include $(SRC_DIR)apps/Makefile.mk
include $(SRC_DIR)chips/Makefile.mk
include $(SRC_DIR)common/Makefile.mk
include $(SRC_DIR)arch/$(ARCH)/Makefile.mk
include $(SRC_DIR)drivers/Makefile.mk
include $(SRC_DIR)hil/Makefile.mk
include $(SRC_DIR)platform/Makefile.mk
include $(SRC_DIR)process/Makefile.mk
include $(SRC_DIR)main/Makefile.mk
